language: python

python:
  - 3.6.8

matrix:

  include:

    - name: "Python 3.7.7 on MacOS 10.14.6"
      os: osx
      osx_image: xcode11.2
      language: shell
      install:
        - python3 --version
        - pip3 install -U pip --user
        - pip3 install -r tests/test_requirements.txt --user
        - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
        - gunzip metis-5.1.0.tar.gz
        - tar -xvf metis-5.1.0.tar
        - rm metis-5.1.0.tar
        - cd metis-5.1.0
        - make config shared=1
        - make install
        # libmetis.dylib on MacOS
        - export METIS_DLL=/usr/local/lib/libmetis.dylib
        - cd ..

    - name: "Python 3.6.8 on Xenial Linux"
      install:
        - pip install -U pip
        - pip install -r tests/test_requirements.txt
        - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
        - gunzip metis-5.1.0.tar.gz
        - tar -xvf metis-5.1.0.tar
        - rm metis-5.1.0.tar
        - cd metis-5.1.0
        - make config prefix=~/ClustViz/METIS_temp shared=1
        - make install
        # libmetis.so on Linux
        - export METIS_DLL=/home/travis/ClustViz/METIS_temp/lib/libmetis.so
        - cd ..

    - name: "Python 3.7.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install -U pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install:
        - pip install -r tests/test_requirements.txt
        - powershell -command "& { iwr https://github.com/guglielmosanchini/conda-metis/archive/master.zip -OutFile conda-metis-master.zip }"
        - powershell -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('conda-metis-master.zip', '.'); }"
        - cd conda-metis-master
        - .\vsgen
        - "C:\ProgramFiles(x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSbuild.exe" build\windows\METIS.sln
        - setx METIS_DLL C:\Users\your_username\Desktop\conda-metis-master\build\windows\libmetis\Release\metis.dll


script:
- python3 -m pytest --cov=clustviz/ --cov-report term-missing --flake8 || python -m pytest --cov=clustviz/ --cov-report term-missing --flake8

after_success:
- python3 -m coveralls

deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/ # remove when using the real pypi
  username: __token__
  password:
    secure: FXYcYrFMKeTbvfXLIQo4YMwQHm8yeDqHPImVbZlKSdel5dFGpxH5ug01ty9zPyU3ldA1DZZp049uIAremr5tr2PR0LJYRsxcP3qEAyvEqsmTp9dQRdFVe1ZBP2ra1ljVujp9ZuJ+IQCzufm9SPtC29cV3XG0IGAy6CScSRZiQxw/kyXUXMXJVGECTuvIkiI9gjjJmzvlanDJcXy0gQFMXK0VMXQ9MCXGDYTs+RGq0VQtrpyeO5WWPkmqqwhga6mXdgbz1I1HGTMDoxHMwvvyNnYi5cZBJyxDcuCZHMart6P4VPM1coMxd+spusfaN5tyGZhmJsmKA9+6/urYrSEfi+DYkcOC8tDGMHxxxJ2lfPd0XS0GnCo9RJrCkGuZcVCBhlggkv2qPVEymSVBkAUZ4IdTkNPfQl25b5L4vKrWAEtIEbKEH17+iPjJbHmuErU860KAe9DRQRIF6k2M7XKF0cqqunWg7MKJXOM6BQBsnH2VOLyKzRC1f9wRFicUdJNYv5SPDWhJj8g+3AlwXEpuaeSWCsZN4H2blB1Z5IoU0TV/hfy5ZdS4CMy6EakpudBUvZZ2ewpOB0ra3UfCHBE/ob126zliC2Mj6nu2fvSn3Imt+Kljh5MeYaagAkuehPoBjE+SlPryWze+VPfJt7J6o0AoYxs7vRxz5lhs52EvO1o=
  skip_existing: true
  on:
    tags: true

notifications:
  email: false
