language: python

python:
- '3.6.8'
# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
  - gunzip metis-5.1.0.tar.gz
  - tar -xvf metis-5.1.0.tar
  - rm metis-5.1.0.tar
  - cd metis-5.1.0
  - make config prefix=~/Clustering/METIS_temp shared=1
  # - make config shared=1
  - make install
  # libmetis.so because we use TravisCI in Ubuntu, otherwise it should be libmetis.dylib
  - export METIS_DLL=/home/travis/Clustering/METIS_temp/lib/libmetis.so
  - cd ..
# command to run tests
script:
  - pytest --cov=code_src/algorithms