language: python

python: # this only works for linux
  - '3.6.8'
# - '3.7'
matrix:
  include:
    - name: "Python 3.7.7 on MacOS 10.14.6"
      os: osx
      osx_image: xcode11.2
      language: shell  # 'language: python' is an error on Travis CI macOS
      install:
        - python3 --version
        - pip3 install -U pip --user  # need to use pip3 instead of pip
        - pip3 install -r tests/test_requirements.txt --user
        - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
        - gunzip metis-5.1.0.tar.gz
        - tar -xvf metis-5.1.0.tar
        - rm metis-5.1.0.tar
        - cd metis-5.1.0
        - make config shared=1
        - make install
        # libmetis.dylib because we are on macOS
        - export METIS_DLL=/usr/local/lib/libmetis.dylib
        - cd ..
    - name: "Python 3.6.8 on Xenial Linux"
      install:
        - pip install -U pip
        - pip install -r tests/test_requirements.txt
        - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
        - gunzip metis-5.1.0.tar.gz
        - tar -xvf metis-5.1.0.tar
        - rm metis-5.1.0.tar
        - cd metis-5.1.0
        - make config prefix=~/ClustViz/METIS_temp shared=1
        - make install
        # libmetis.so because we are on Ubuntu
        - export METIS_DLL=/home/travis/ClustViz/METIS_temp/lib/libmetis.so
        - cd ..
# command to run tests, code coverage also reporting missing code lines, flake8 style check
script:
  - python3 -m pytest --cov=clustviz/algorithms --cov-report term-missing --flake8

after_success:
  - python3 -m coveralls  # command to visualize coverage report on coveralls.io

notifications:
  email: false
