name: prova windows

on: [push]

jobs:
  build:

    runs-on: [windows-latest]
    #runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [3.6]

    steps:
    - name: setup-msbuild # install Visual Studio Code
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/test_requirements.txt
        iwr https://github.com/guglielmosanchini/conda-metis/archive/master.zip -OutFile conda-metis-master.zip
        Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('conda-metis-master.zip', '.')
        cd clustviz
        New-Item conftest.py
        ls
        cd ..
        python -m pytest --collect-only
        cd conda-metis-master
        ./prova.bat # moved upwards
        ./vsgen.bat
        pwd
        cd build/windows
        MSBuild.exe METIS.sln /p:Configuration=Release
        cd libmetis/Release
        ls
        cd ../../../..
        python -m pytest --collect-only
        python -m pytest
      env:
        METIS_DLL: D:\a\ClustViz\ClustViz\conda-metis-master\build\windows\libmetis\Release\metis.dll