name: reg attempt

on: [push]

jobs:
  windows_job:
    name: Windows job
    runs-on: [windows-latest]
    #runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [3.6]

    steps:
    #- name: setup-msbuild # install Visual Studio Code
    #  uses: microsoft/setup-msbuild@v1

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      # C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
    - name:
      run: |
        echo "::add-path::C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
    - name: reg query
      run: |
        reg add HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\4.0 /v MSBuildOverrideTasksPath /d "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\" /f
        reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\4.0
        reg add HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0 /v MSBuildToolPath /d "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\15.0\Bin\" /f
        reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install metis
        # python -m pip install -r tests/test_requirements.txt

    - name: Download conda-metis
      run: |
        iwr https://github.com/guglielmosanchini/conda-metis/archive/master.zip -OutFile conda-metis-master.zip
        Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('conda-metis-master.zip', '.')

    - name: Generate VS files
      run: |
        cd conda-metis-master
        ./prova.bat # moved upwards
        cmake --help
        ./vsgen -G "Visual Studio 15 2017 Win64"
        #./vsgen.bat

    - name: Build with Visual Studio Code (this step fails but it doesnt matter)
      run: |
        cd conda-metis-master/build/windows
        MSBuild.exe METIS.sln
        # MSBuild.exe METIS.sln /p:Configuration=Release
