name: prova_both

on: [push]

jobs:
  windows_job:
    name: Windows job
    runs-on: [windows-latest]
    #runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.6", "3.7", "3.8"]

    steps:
    - name: setup-msbuild # install Visual Studio Code
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/test_requirements.txt
    - name: Download conda-metis
      run: |
        iwr https://github.com/guglielmosanchini/conda-metis/archive/master.zip -OutFile conda-metis-master.zip
        Add-Type -A 'System.IO.Compression.FileSystem'; [IO.Compression.ZipFile]::ExtractToDirectory('conda-metis-master.zip', '.')
    - name: Generate VS files
      run: |
        cd conda-metis-master
        ./prova.bat # moved upwards
        ./vsgen.bat
    - name: Build with Visual Studio Code (this step fails but it doesnt matter)
      run: |
        cd conda-metis-master/build/windows
        MSBuild.exe METIS.sln /p:Configuration=Release
    - name: Perform tests
      if: always() # otherwise it would not be executed, since the previous step failed
      run: |
        python -m pytest --cov=clustviz/ --cov-report term-missing --flake8
      env:
        METIS_DLL: D:\a\ClustViz\ClustViz\conda-metis-master\build\windows\libmetis\Release\metis.dll

  unix_job:
    name: Unix job
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tests/test_requirements.txt
      - name: Download metis from website
        run: |
          wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
          gunzip metis-5.1.0.tar.gz
          tar -xvf metis-5.1.0.tar
          rm metis-5.1.0.tar
      - name: Make
        run: |
          cd metis-5.1.0
          make config shared=1
          make
          echo $RUNNER_OS
      - name: setting env
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo "::set-env name=METIS_DLL::/home/runner/work/ClustViz/ClustViz/metis-5.1.0/build/Linux-x86_64/libmetis/libmetis.so"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "::set-env name=METIS_DLL::/usr/local/lib/libmetis.dylib"
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Perform tests
        if: always() # otherwise it would not be executed, since the previous step failed
        run: |
          python3 -m pytest --cov=clustviz/ --cov-report term-missing --flake8
        #env:
        #  METIS_DLL: /home/runner/work/ClustViz/ClustViz/metis-5.1.0/build/Linux-x86_64/libmetis/libmetis.so
