name: reg attempt

on: [push]

jobs:
  windows_job:
    name: Windows job
    runs-on: [windows-latest]
    #runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [3.6]

    steps:
    - name: setup-msbuild # install Visual Studio Code
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: reg query
      run: |
        reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\4.0
        reg query HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0



