name: prova solo test

on: [push]

jobs:
  build:

    runs-on: [windows-latest]
    #runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        #os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: [3.6]

    steps:
    - name: setup-msbuild # install Visual Studio Code
      uses: microsoft/setup-msbuild@v1
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/test_requirements.txt
        python -m pytest
        #cd clustviz
        #New-Item conftest.py >$null
        #ls
        #cd ..
        #python -m pytest --collect-only